/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package labbion;


import java.util.Scanner;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.IOException;
import java.util.Objects;


public class App 
{
    public static void main(String[] args) 
    {
        System.out.println("start");
        Scanner in = new Scanner(System.in);
        String tmp;
        FileReader input = null;
        FileWriter output = null;
        BufferedReader reader = null;
        try
        {
            input = new FileReader("input.fastq");
            reader = new BufferedReader(input);
            output = new FileWriter("output.fasta", false);
        }
        catch (Exception e)
        {
            System.out.println("Error open file: " + e.getMessage());
            return;
        }
        
        
        try
        {
            tmp = reader.readLine();
        } catch (Exception e) {
            System.out.println("Error read input file");
            return;
        }
        while(!Objects.equals(tmp, "") && tmp != null)
        {
            if (tmp.charAt(0) == '@')
            {
                try {
                    output.append('>');
                    output.write(tmp.substring(1));
                    output.append('\n');
                } catch (Exception e) {
                    System.out.println("Error write output file: " + e.getMessage() );
                    return;
                }
                
                try {
                    tmp = reader.readLine();
                } catch (Exception e) {
                    System.out.println("Error read input file");
                   return;
                }
                
                try {
                    for (int i = 0; i < tmp.length(); i+=60)
                    {
                       output.write(tmp.substring(i, Math.min(i + 60, tmp.length())));
                        //output.write(tmp, i, 60);
                        output.append('\n');
                    }
                } catch (Exception e) {
                    System.out.println("Error write output file: " + e.getMessage() );
                    return;
                }
                try {
                    reader.readLine();
                    reader.readLine();
                } catch (Exception e) {
                    System.out.println("Error read input file");
                   return;
                }
            }
            try
            {
                tmp = reader.readLine();
            } catch (Exception e) {
                System.out.println("Error read input file");
                return;
            }
            try {
                    output.flush();
                } catch (Exception e) {
                    System.out.println("Error flush output file");
                   return;
                }
            
        }
        System.out.println("end");
    }
}
