/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package labbion;


import java.io.FileReader;
import java.io.BufferedReader;
import java.io.IOException;


public class App 
{
    public static int getavg(String str)
    {
        int sum = 0;
        for (int i = 0; i < str.length(); i++)
        {
            sum += str.charAt(i) - 33;
        }
        return sum/str.length();
    }
    
    public static void main(String[] args) 
    {
        String tmp;
        FileReader input;
        BufferedReader reader;
        int count = 0;
        int avgqual;
        try
        {
            input = new FileReader("input.fastq");
            reader = new BufferedReader(input);
        }
        catch (IOException e)
        {
            System.out.println("Error open input file: " + e.getMessage());
            return;
        }
        
        try
        {
            avgqual = Integer.parseInt(reader.readLine());
            tmp = reader.readLine();
            while(tmp != null)
            {
                if (tmp.charAt(0) == '@')
                {
                    reader.readLine();
                    reader.readLine();
                    tmp = reader.readLine();
                    if (tmp == null)
                    {
                        System.out.println("Error format");
                        return;
                    }
                    if (getavg(tmp) < avgqual)
                        count++;
                }
                tmp = reader.readLine();
            }
        } catch (IOException e) {
            System.out.println("Error read input file: " + e.getMessage());
        }
        System.out.println(count);
    }
}
